<?php

/**
 * This file is part of the reliforp/reli-prof package.
 *
 * (c) sji <sji@sj-i.dev>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Reli\Lib\Session;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Reli\Lib\Session\Attribute\SessionProtocol;

final class RecvBranchExhaustivenessCheckerTest extends TestCase
{
    private string $tmpDir;

    protected function setUp(): void
    {
        $this->tmpDir = sys_get_temp_dir() . '/exhaustiveness_test_' . uniqid();
        mkdir($this->tmpDir, 0755, true);
    }

    protected function tearDown(): void
    {
        $this->removeDir($this->tmpDir);
    }

    private function removeDir(string $dir): void
    {
        foreach (scandir($dir) as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }
            $path = $dir . '/' . $item;
            is_dir($path) ? $this->removeDir($path) : unlink($path);
        }
        rmdir($dir);
    }

    private function writeFile(string $name, string $content): void
    {
        file_put_contents($this->tmpDir . '/' . $name, $content);
    }

    #[Test]
    public function no_warnings_when_all_types_checked(): void
    {
        $this->writeFile('Consumer.php', <<<'PHP'
        <?php
        $result = $protocol->receiveAlphaOrBeta();
        if ($result instanceof AlphaMessage) {
            handleAlpha($result);
        } elseif ($result instanceof BetaMessage) {
            handleBeta($result);
        }
        PHP);

        $method = new BranchRecvMethod(
            state: 'Waiting',
            methodName: 'receiveAlphaOrBeta',
            messageClasses: ['App\\AlphaMessage', 'App\\BetaMessage'],
            messageClassShortNames: ['AlphaMessage', 'BetaMessage'],
        );

        $checker = new RecvBranchExhaustivenessChecker();
        $warnings = $checker->check([$method], $this->tmpDir);

        $this->assertSame([], $warnings);
    }

    #[Test]
    public function warns_when_type_missing_instanceof(): void
    {
        $this->writeFile('Consumer.php', <<<'PHP'
        <?php
        $result = $protocol->receiveAlphaOrBeta();
        if ($result instanceof AlphaMessage) {
            handleAlpha($result);
        } else {
            // BetaMessage handled implicitly — no instanceof
            handleOther($result);
        }
        PHP);

        $method = new BranchRecvMethod(
            state: 'Waiting',
            methodName: 'receiveAlphaOrBeta',
            messageClasses: ['App\\AlphaMessage', 'App\\BetaMessage'],
            messageClassShortNames: ['AlphaMessage', 'BetaMessage'],
        );

        $checker = new RecvBranchExhaustivenessChecker();
        $warnings = $checker->check([$method], $this->tmpDir);

        $this->assertCount(1, $warnings);
        $this->assertStringContainsString('BetaMessage', $warnings[0]);
        $this->assertStringContainsString('never checked', $warnings[0]);
    }

    #[Test]
    public function class_constant_syntax_counts_as_checked(): void
    {
        $this->writeFile('Consumer.php', <<<'PHP'
        <?php
        $result = $protocol->receiveAlphaOrBeta();
        match (true) {
            $result instanceof AlphaMessage => handleAlpha($result),
            $result instanceof BetaMessage::class => handleBeta($result),
        };
        PHP);

        // BetaMessage::class also counted
        $method = new BranchRecvMethod(
            state: 'Waiting',
            methodName: 'receiveAlphaOrBeta',
            messageClasses: ['App\\AlphaMessage', 'App\\BetaMessage'],
            messageClassShortNames: ['AlphaMessage', 'BetaMessage'],
        );

        $checker = new RecvBranchExhaustivenessChecker();
        $warnings = $checker->check([$method], $this->tmpDir);

        $this->assertSame([], $warnings);
    }

    #[Test]
    public function skips_generated_protocol_files(): void
    {
        $this->writeFile('Generated.php', <<<'PHP'
        <?php
        /**
         * @generated by session-protocol-generator from TestSession
         */
        $result = $protocol->receiveAlphaOrBeta();
        return $result;
        PHP);

        $method = new BranchRecvMethod(
            state: 'Waiting',
            methodName: 'receiveAlphaOrBeta',
            messageClasses: ['App\\AlphaMessage', 'App\\BetaMessage'],
            messageClassShortNames: ['AlphaMessage', 'BetaMessage'],
        );

        $checker = new RecvBranchExhaustivenessChecker();
        $warnings = $checker->check([$method], $this->tmpDir);

        $this->assertSame([], $warnings);
    }

    #[Test]
    public function no_warnings_when_no_branch_methods(): void
    {
        $checker = new RecvBranchExhaustivenessChecker();
        $warnings = $checker->check([], $this->tmpDir);

        $this->assertSame([], $warnings);
    }

    #[Test]
    public function no_warnings_when_no_call_sites_found(): void
    {
        $this->writeFile('Unrelated.php', <<<'PHP'
        <?php
        // This file doesn't call the method at all
        doSomethingElse();
        PHP);

        $method = new BranchRecvMethod(
            state: 'Waiting',
            methodName: 'receiveAlphaOrBeta',
            messageClasses: ['App\\AlphaMessage', 'App\\BetaMessage'],
            messageClassShortNames: ['AlphaMessage', 'BetaMessage'],
        );

        $checker = new RecvBranchExhaustivenessChecker();
        $warnings = $checker->check([$method], $this->tmpDir);

        $this->assertSame([], $warnings);
    }

    #[Test]
    public function extractBranchRecvMethods_identifies_branching_recv(): void
    {
        $graph = new SessionGraph(
            protocol: new SessionProtocol(
                name: 'Test',
                workerNamespace: 'App\\Worker',
                controllerNamespace: 'App\\Controller',
            ),
            initialState: 'Waiting',
            transitions: [
                'Waiting' => [
                    new SessionTransition(Direction::Recv, \stdClass::class, 'Waiting'),
                    new SessionTransition(Direction::Recv, \ArrayObject::class, 'Waiting'),
                ],
            ],
        );

        $methods = RecvBranchExhaustivenessChecker::extractBranchRecvMethods($graph);

        $this->assertCount(1, $methods);
        $this->assertSame('receivestdClassOrArrayObject', $methods[0]->methodName);
        $this->assertSame(['stdClass', 'ArrayObject'], $methods[0]->messageClassShortNames);
    }

    #[Test]
    public function extractBranchRecvMethods_skips_single_recv(): void
    {
        $graph = new SessionGraph(
            protocol: new SessionProtocol(
                name: 'Test',
                workerNamespace: 'App\\Worker',
                controllerNamespace: 'App\\Controller',
            ),
            initialState: 'Waiting',
            transitions: [
                'Waiting' => [
                    new SessionTransition(Direction::Recv, \stdClass::class, 'Waiting'),
                ],
            ],
        );

        $methods = RecvBranchExhaustivenessChecker::extractBranchRecvMethods($graph);
        $this->assertSame([], $methods);
    }

    #[Test]
    public function extractBranchRecvMethods_skips_branching_send(): void
    {
        $graph = new SessionGraph(
            protocol: new SessionProtocol(
                name: 'Test',
                workerNamespace: 'App\\Worker',
                controllerNamespace: 'App\\Controller',
            ),
            initialState: 'Choosing',
            transitions: [
                'Choosing' => [
                    new SessionTransition(Direction::Send, \stdClass::class, 'Choosing'),
                    new SessionTransition(Direction::Send, \ArrayObject::class, 'Choosing'),
                ],
            ],
        );

        $methods = RecvBranchExhaustivenessChecker::extractBranchRecvMethods($graph);
        $this->assertSame([], $methods);
    }

    #[Test]
    public function real_protocol_exhaustiveness_passes(): void
    {
        $graph = SessionGraph::fromEnum(
            \Reli\Inspector\Daemon\Reader\Protocol\PhpReaderSession::class,
        );
        $methods = RecvBranchExhaustivenessChecker::extractBranchRecvMethods($graph);

        $checker = new RecvBranchExhaustivenessChecker();
        $srcDir = dirname(__DIR__, 3) . '/src';
        $warnings = $checker->check($methods, $srcDir);

        $this->assertSame([], $warnings, implode("\n", $warnings));
    }
}
