#!/usr/bin/env php
<?php

/**
 * This file is part of the sj-i/php-profiler package.
 *
 * (c) sji <sji@sj-i.dev>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use PhpProfiler\Command\CommandEnumerator;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$application = new Application();

foreach (new CommandEnumerator() as $command_class) {
    $application->add(new $command_class);
}

$application->run();