<?php

/**
 * This file is part of the reliforp/reli-prof package.
 *
 * (c) sji <sji@sj-i.dev>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Reli\Inspector\MemoryDump\FastPath;

/**
 * Read Zend structures from dump regions without FFI.
 *
 * Per-version implementations are generated by
 * tools/generate-offset-readers.php with field offsets and
 * primitive reads inlined for JIT-friendly instance method dispatch.
 */
interface FastPathReader
{
    // ---- Zval ----
    public function zvalType(int $address): ?int;
    public function zvalValuePtr(int $address): ?int;
    public function zvalValueLval(int $address): ?int;
    public function zvalTypeInfo(int $address): ?int;

    // ---- Bucket ----
    public function bucketValType(int $address): ?int;
    public function bucketValValuePtr(int $address): ?int;
    public function bucketKeyPtr(int $address): ?int;
    public function bucketH(int $address): ?int;

    // ---- ZendArray ----
    public function arrayArData(int $address): ?int;
    public function arrayFlags(int $address): ?int;
    public function arrayNTableMask(int $address): ?int;
    public function arrayNNumUsed(int $address): ?int;
    public function arrayNNumOfElements(int $address): ?int;
    public function arrayNTableSize(int $address): ?int;
    public function arrayRefcount(int $address): ?int;
    public function arrayTypeInfo(int $address): ?int;

    // ---- ZendString ----
    public function stringLen(int $address): ?int;
    public function stringH(int $address): ?int;
    public function stringVal(int $address, int $len): ?string;
    public function stringRefcount(int $address): ?int;
    public function stringTypeInfo(int $address): ?int;

    // ---- ZendObject ----
    public function objectCe(int $address): ?int;
    public function objectHandle(int $address): ?int;
    public function objectHandlers(int $address): ?int;
    public function objectPropertiesTable(int $address): ?int;
    public function objectProperties(int $address): ?int;
    public function objectRefcount(int $address): ?int;
    public function objectTypeInfo(int $address): ?int;

    // ---- Class Entry Cache ----

    /**
     * Resolve class_name for a ce address, caching the result.
     * Returns null if the address is not in a dump region.
     * The first call for a given ce_addr reads the name via string
     * chain; subsequent calls return the cached value.
     *
     * @return array{class_name: string, default_properties_count: int}|null
     */
    public function resolveClassEntry(int $ce_addr): ?array;

    // ---- Sizes ----
    public function zvalSize(): int;
    public function bucketSize(): int;
    public function arraySize(): int;
    /**
     * Size of the zend_string fixed header (excluding val[]).
     * Equal to the offset of the val field, NOT sizeof(zend_string).
     * Use this for MemoryLocation size calculation: header + strlen.
     */
    public function stringHeaderSize(): int;
    public function objectHeaderSize(): int;
    /** Offset of zend_string.val within the struct. */
    public function stringValOffset(): int;
}
