<?php

/**
 * This file is part of the reliforp/reli-prof package.
 *
 * (c) sji <sji@sj-i.dev>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @generated by session-protocol-generator from PhpReaderSession
 */

declare(strict_types=1);

namespace Reli\Inspector\Daemon\Reader\Worker;

use Amp\Sync\Channel;
use Reli\Inspector\Daemon\Reader\Protocol\Message\AttachMessage;
use Reli\Inspector\Daemon\Reader\Protocol\Message\DetachWorkerMessage;
use Reli\Inspector\Daemon\Reader\Protocol\Message\SetSettingsMessage;
use Reli\Inspector\Daemon\Reader\Protocol\Message\TraceMessage;
use Reli\Inspector\Daemon\Reader\Protocol\PhpReaderSession;
use Reli\Inspector\Daemon\Reader\Protocol\PhpReaderWorkerProtocolInterface;

/**
 * @template TState of PhpReaderSession
 * @implements PhpReaderWorkerProtocolInterface<TState>
 */
final class PhpReaderWorkerProtocol implements PhpReaderWorkerProtocolInterface
{
    public function __construct(
private Channel $channel
    ) {
    }

    /** @return self<PhpReaderSession::AwaitingSettings> */
    public static function createFromChannel(Channel $channel): static
    {
return new self($channel);
    }

    /**
     * @psalm-if-this-is PhpReaderWorkerProtocol<PhpReaderSession::Tracing>
     * @psalm-this-out PhpReaderWorkerProtocol<PhpReaderSession::Tracing>
     */
    public function sendTrace(TraceMessage $message): void
    {
$this->channel->send($message);
    }

    /**
     * @psalm-if-this-is PhpReaderWorkerProtocol<PhpReaderSession::Tracing>
     * @psalm-this-out PhpReaderWorkerProtocol<PhpReaderSession::AwaitingAttach>
     */
    public function sendDetachWorker(DetachWorkerMessage $message): void
    {
$this->channel->send($message);
    }

    /**
     * @psalm-if-this-is PhpReaderWorkerProtocol<PhpReaderSession::AwaitingSettings>
     * @psalm-this-out PhpReaderWorkerProtocol<PhpReaderSession::AwaitingAttach>
     */
    public function receiveSetSettings(): SetSettingsMessage
    {
/** @var SetSettingsMessage */
return $this->channel->receive();
    }

    /**
     * @psalm-if-this-is PhpReaderWorkerProtocol<PhpReaderSession::AwaitingAttach>
     * @psalm-this-out PhpReaderWorkerProtocol<PhpReaderSession::Tracing>
     */
    public function receiveAttach(): AttachMessage
    {
/** @var AttachMessage */
return $this->channel->receive();
    }
}
