<?php

/**
 * This file is part of the reliforp/reli-prof package.
 *
 * (c) sji <sji@sj-i.dev>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Reli\Lib\Session\Generator;

use Reli\Lib\Session\Direction;
use Reli\Lib\Session\SessionGraph;
use Reli\Lib\Session\SessionTransition;

final class ProtocolGenerator
{
    /**
     * @return array<string, string> filename => content
     */
    public function generate(SessionGraph $graph): array
    {
        $errors = $graph->verify();
        if ($errors !== []) {
            throw new \RuntimeException(
                "Protocol verification failed:\n" . implode("\n", $errors)
            );
        }

        $files = [];

        // Worker side: same direction as definition
        $files += $this->generateInterface($graph, Side::Worker);
        $files += $this->generateImplementation($graph, Side::Worker);

        // Controller side: dual direction
        $files += $this->generateInterface($graph, Side::Controller);
        $files += $this->generateImplementation($graph, Side::Controller);

        return $files;
    }

    /**
     * @return array<string, string>
     */
    private function generateInterface(SessionGraph $graph, Side $side): array
    {
        $name = $graph->protocol->name;
        $namespace = $this->protocolNamespace($graph);
        $className = "{$name}{$side->label()}ProtocolInterface";
        $enumShort = $this->shortName($graph->enumClass ?? '');

        $uses = [
            'Reli\Lib\Amphp\MessageProtocolInterface',
        ];
        if ($graph->enumClass !== null) {
            $uses[] = $graph->enumClass;
        }
        $methods = [];

        foreach ($graph->transitions as $state => $transitions) {
            foreach ($transitions as $transition) {
                $dir = $side === Side::Controller ? $transition->direction->dual() : $transition->direction;
                $messageShort = $this->shortName($transition->messageClass);
                $uses[] = $transition->messageClass;

                if ($dir === Direction::Send) {
                    $methodName = $this->sendMethodName($graph, $state, $transition);
                    $doc = $this->psalmMethodDoc($className, $enumShort, $state, [$transition->nextState], '    ');
                    $methods[] = "{$doc}\n    public function {$methodName}({$messageShort} \$message): void;";
                }
            }
        }

        // Generate receive methods: group by state for Recv (worker) / Send (controller=dual recv)
        foreach ($graph->transitions as $state => $transitions) {
            $dir = $side === Side::Controller
                ? $transitions[0]->direction->dual()
                : $transitions[0]->direction;

            if ($dir !== Direction::Recv) {
                continue;
            }

            $nextStates = array_unique(array_map(fn (SessionTransition $t) => $t->nextState, $transitions));
            $doc = $this->psalmMethodDoc($className, $enumShort, $state, $nextStates, '    ');

            if (count($transitions) === 1) {
                $t = $transitions[0];
                $messageShort = $this->shortName($t->messageClass);
                $methodName = $this->recvMethodName($graph, $state, $transitions);
                $methods[] = "{$doc}\n    public function {$methodName}(): {$messageShort};";
            } else {
                $returnTypes = array_map(
                    fn (SessionTransition $t) => $this->shortName($t->messageClass),
                    $transitions
                );
                $methodName = $this->recvMethodName($graph, $state, $transitions);
                $methods[] = "{$doc}\n    public function {$methodName}(): " . implode('|', $returnTypes) . ";";
            }
        }

        $uses = array_unique($uses);
        sort($uses);

        $useLines = implode("\n", array_map(fn (string $u) => "use {$u};", $uses));
        $methodBlock = implode("\n\n", $methods);
        $templateDoc = $graph->enumClass !== null
            ? "/**\n * @template TState of {$enumShort}\n */\n"
            : '';

        $content = <<<PHP
        <?php

        /**
         * This file is part of the reliforp/reli-prof package.
         *
         * (c) sji <sji@sj-i.dev>
         *
         * For the full copyright and license information, please view the LICENSE
         * file that was distributed with this source code.
         *
         * @generated by session-protocol-generator from {$graph->protocol->name}Session
         */

        declare(strict_types=1);

        namespace {$namespace};

        {$useLines}

        {$templateDoc}interface {$className} extends MessageProtocolInterface
        {
        {$methodBlock}
        }

        PHP;

        $filePath = $this->namespaceToPath($namespace) . "/{$className}.php";
        return [$filePath => $this->normalizeIndent($content)];
    }

    /**
     * @return array<string, string>
     */
    private function generateImplementation(SessionGraph $graph, Side $side): array
    {
        $name = $graph->protocol->name;
        $protocolNamespace = $this->protocolNamespace($graph);
        $implNamespace = $side === Side::Worker
            ? $graph->protocol->workerNamespace
            : $graph->protocol->controllerNamespace;
        $interfaceName = "{$name}{$side->label()}ProtocolInterface";
        $className = "{$name}{$side->label()}Protocol";
        $enumShort = $this->shortName($graph->enumClass ?? '');

        $uses = [
            'Amp\Sync\Channel',
            "{$protocolNamespace}\\{$interfaceName}",
        ];
        if ($graph->enumClass !== null) {
            $uses[] = $graph->enumClass;
        }

        $methods = [];

        // Send methods
        foreach ($graph->transitions as $state => $transitions) {
            foreach ($transitions as $transition) {
                $dir = $side === Side::Controller ? $transition->direction->dual() : $transition->direction;
                $messageShort = $this->shortName($transition->messageClass);
                $uses[] = $transition->messageClass;

                if ($dir === Direction::Send) {
                    $methodName = $this->sendMethodName($graph, $state, $transition);
                    $doc = $this->psalmMethodDoc($className, $enumShort, $state, [$transition->nextState]);
                    $methods[] = ($doc !== '' ? $doc . "\n" : '') .
                        "public function {$methodName}({$messageShort} \$message): void\n" .
                        "{\n" .
                        "    \$this->channel->send(\$message);\n" .
                        '}';
                }
            }
        }

        // Receive methods
        foreach ($graph->transitions as $state => $transitions) {
            $dir = $side === Side::Controller
                ? $transitions[0]->direction->dual()
                : $transitions[0]->direction;

            if ($dir !== Direction::Recv) {
                continue;
            }

            $nextStates = array_unique(array_map(fn (SessionTransition $t) => $t->nextState, $transitions));
            $doc = $this->psalmMethodDoc($className, $enumShort, $state, $nextStates);

            if (count($transitions) === 1) {
                $t = $transitions[0];
                $messageShort = $this->shortName($t->messageClass);
                $methodName = $this->recvMethodName($graph, $state, $transitions);
                $methods[] = ($doc !== '' ? $doc . "\n" : '') .
                    "public function {$methodName}(): {$messageShort}\n" .
                    "{\n" .
                    "    /** @var {$messageShort} */\n" .
                    "    return \$this->channel->receive();\n" .
                    '}';
            } else {
                $returnTypes = array_map(
                    fn (SessionTransition $t) => $this->shortName($t->messageClass),
                    $transitions
                );
                $returnType = implode('|', $returnTypes);
                $methodName = $this->recvMethodName($graph, $state, $transitions);
                $methods[] = ($doc !== '' ? $doc . "\n" : '') .
                    "public function {$methodName}(): {$returnType}\n" .
                    "{\n" .
                    "    /** @var {$returnType} */\n" .
                    "    return \$this->channel->receive();\n" .
                    '}';
            }
        }

        $uses = array_unique($uses);
        sort($uses);

        $useLines = implode("\n", array_map(fn (string $u) => "use {$u};", $uses));
        $methodBlock = implode("\n\n", array_map(fn (string $m) => $this->indentBlock($m, 1), $methods));

        $templateDoc = '';
        $implementsClause = "implements {$interfaceName}";
        $createFromChannelDoc = '';
        if ($graph->enumClass !== null) {
            $templateDoc = "/**\n * @template TState of {$enumShort}\n * @implements {$interfaceName}<TState>\n */\n";
            $createFromChannelDoc = "    /** @return self<{$enumShort}::{$graph->initialState}> */\n";
        }

        $content = <<<PHP
        <?php

        /**
         * This file is part of the reliforp/reli-prof package.
         *
         * (c) sji <sji@sj-i.dev>
         *
         * For the full copyright and license information, please view the LICENSE
         * file that was distributed with this source code.
         *
         * @generated by session-protocol-generator from {$graph->protocol->name}Session
         */

        declare(strict_types=1);

        namespace {$implNamespace};

        {$useLines}

        {$templateDoc}final class {$className} {$implementsClause}
        {
            public function __construct(
                private Channel \$channel
            ) {
            }

        {$createFromChannelDoc}    public static function createFromChannel(Channel \$channel): static
            {
                return new self(\$channel);
            }

        {$methodBlock}
        }

        PHP;

        $filePath = $this->namespaceToPath($implNamespace) . "/{$className}.php";
        return [$filePath => $this->normalizeIndent($content)];
    }

    private function sendMethodName(SessionGraph $graph, string $state, SessionTransition $transition): string
    {
        $messageShort = $this->shortName($transition->messageClass);
        // Remove 'Message' suffix for method name
        $baseName = preg_replace('/Message$/', '', $messageShort);
        return 'send' . $baseName;
    }

    /**
     * @param list<SessionTransition> $transitions
     */
    private function recvMethodName(SessionGraph $graph, string $state, array $transitions): string
    {
        if (count($transitions) === 1) {
            $messageShort = $this->shortName($transitions[0]->messageClass);
            $baseName = preg_replace('/Message$/', '', $messageShort);
            return 'receive' . $baseName;
        }

        $names = array_map(function (SessionTransition $t) {
            $short = $this->shortName($t->messageClass);
            return preg_replace('/Message$/', '', $short);
        }, $transitions);

        return 'receive' . implode('Or', $names);
    }

    /**
     * @param list<string> $nextStates
     */
    private function psalmMethodDoc(string $className, string $enumShort, string $state, array $nextStates, string $indent = ''): string
    {
        if ($enumShort === '') {
            return '';
        }
        $ifThis = "{$className}<{$enumShort}::{$state}>";
        $outStates = implode('|', array_map(fn (string $s) => "{$enumShort}::{$s}", $nextStates));
        $thisOut = "{$className}<{$outStates}>";

        return "{$indent}/**\n" .
            "{$indent} * @psalm-if-this-is {$ifThis}\n" .
            "{$indent} * @psalm-this-out {$thisOut}\n" .
            "{$indent} */";
    }

    private function shortName(string $fqcn): string
    {
        $parts = explode('\\', $fqcn);
        return end($parts);
    }

    private function protocolNamespace(SessionGraph $graph): string
    {
        // Derive from worker namespace: go up one level and add Protocol
        // e.g., Reli\Inspector\Daemon\Reader\Worker -> Reli\Inspector\Daemon\Reader\Protocol
        $workerNs = $graph->protocol->workerNamespace;
        $parts = explode('\\', $workerNs);
        array_pop($parts); // remove 'Worker'
        $parts[] = 'Protocol';
        return implode('\\', $parts);
    }

    private function namespaceToPath(string $namespace): string
    {
        // Reli\... -> src/...
        $relative = str_replace('Reli\\', '', $namespace);
        return 'src/' . str_replace('\\', '/', $relative);
    }

    private function normalizeIndent(string $content): string
    {
        // Remove the heredoc indentation (8 spaces from the class method)
        $lines = explode("\n", $content);
        $result = [];
        foreach ($lines as $line) {
            // Remove up to 8 leading spaces (heredoc indent)
            $result[] = preg_replace('/^        /', '', $line);
        }
        return implode("\n", $result);
    }

    private function indentBlock(string $block, int $level): string
    {
        $indent = str_repeat('    ', $level);
        $lines = explode("\n", $block);
        return implode("\n", array_map(
            fn (string $line) => $line === '' ? '' : $indent . $line,
            $lines
        ));
    }
}
