<?php

/**
 * This file is part of the reliforp/reli-prof package.
 *
 * (c) sji <sji@sj-i.dev>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Reli\Lib\Dwarf;

/**
 * Reads /tmp/perf-<pid>.map files generated by PHP JIT (opcache.jit_debug=0x10).
 *
 * File format: one line per JIT-compiled function
 *   <hex_address> <hex_size> <symbol_name>
 *
 * Example:
 *   7f1234567000 1a0 JIT$MyClass::myMethod
 *   7f12345671a0 80  JIT$fibonacci
 */
final class PerfMapSymbolResolver
{
    /** @var array{int, int, string}[] sorted by address: [address, size, name] */
    private array $entries = [];

    private bool $loaded = false;

    public function __construct(
        private int $pid,
    ) {
    }

    /**
     * @return array{string, int}|null [symbolName, offset] or null
     */
    public function resolve(int $address): ?array
    {
        if (!$this->loaded) {
            $this->load();
        }

        if ($this->entries === []) {
            return null;
        }

        // Binary search
        $lo = 0;
        $hi = count($this->entries) - 1;
        $candidate = null;

        while ($lo <= $hi) {
            $mid = intdiv($lo + $hi, 2);
            if ($this->entries[$mid][0] <= $address) {
                $candidate = $mid;
                $lo = $mid + 1;
            } else {
                $hi = $mid - 1;
            }
        }

        if ($candidate === null) {
            return null;
        }

        [$sym_addr, $sym_size, $sym_name] = $this->entries[$candidate];
        $offset = $address - $sym_addr;

        if ($sym_size > 0 && $offset >= $sym_size) {
            return null;
        }

        return [$sym_name, $offset];
    }

    public function reload(): void
    {
        $this->loaded = false;
        $this->entries = [];
    }

    private function load(): void
    {
        $this->loaded = true;
        $path = "/tmp/perf-{$this->pid}.map";

        if (!is_file($path)) {
            return;
        }

        $contents = file_get_contents($path);
        if ($contents === false) {
            return;
        }

        $entries = [];
        foreach (explode("\n", $contents) as $line) {
            $line = trim($line);
            if ($line === '') {
                continue;
            }

            // Format: <hex_address> <hex_size> <name>
            $parts = preg_split('/\s+/', $line, 3);
            if ($parts === false || count($parts) < 3) {
                continue;
            }

            $address = hexdec($parts[0]);
            $size = hexdec($parts[1]);
            $name = $parts[2];

            if ($address === 0 || $name === '') {
                continue;
            }

            $entries[] = [$address, $size, $name];
        }

        usort($entries, /** @param array{int, int, string} $a @param array{int, int, string} $b */ fn(array $a, array $b) => $a[0] <=> $b[0]);
        $this->entries = $entries;
    }
}
