<?php

/**
 * This file is part of the reliforp/reli-prof package.
 *
 * (c) sji <sji@sj-i.dev>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Reli\Lib\Session\Generator;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Reli\Inspector\Daemon\Reader\Protocol\PhpReaderSession;
use Reli\Inspector\Daemon\Searcher\Protocol\PhpSearcherSession;
use Reli\Lib\Session\Attribute\SessionProtocol;
use Reli\Lib\Session\Direction;
use Reli\Lib\Session\SessionGraph;
use Reli\Lib\Session\SessionTransition;

// Test-only stub message classes
class PingMessage
{
}
class PongMessage
{
}
class FooMessage
{
}
class BarMessage
{
}

final class ProtocolGeneratorTest extends TestCase
{
    private ProtocolGenerator $generator;

    protected function setUp(): void
    {
        $this->generator = new ProtocolGenerator();
    }

    private function simpleGraph(): SessionGraph
    {
        return new SessionGraph(
            protocol: new SessionProtocol(
                name: 'Test',
                workerNamespace: 'App\\Worker',
                controllerNamespace: 'App\\Controller',
            ),
            initialState: 'Ready',
            transitions: [
                'Ready' => [
                    new SessionTransition(Direction::Recv, PingMessage::class, 'Responding'),
                ],
                'Responding' => [
                    new SessionTransition(Direction::Send, PongMessage::class, 'Ready'),
                ],
            ],
        );
    }

    #[Test]
    public function generates_four_files(): void
    {
        $files = $this->generator->generate($this->simpleGraph());

        $this->assertCount(4, $files);
        $paths = array_keys($files);
        $this->assertContains('src/App/Protocol/TestWorkerProtocolInterface.php', $paths);
        $this->assertContains('src/App/Worker/TestWorkerProtocol.php', $paths);
        $this->assertContains('src/App/Protocol/TestControllerProtocolInterface.php', $paths);
        $this->assertContains('src/App/Controller/TestControllerProtocol.php', $paths);
    }

    #[Test]
    public function worker_interface_has_send_and_receive_methods(): void
    {
        $files = $this->generator->generate($this->simpleGraph());
        $content = $files['src/App/Protocol/TestWorkerProtocolInterface.php'];

        // Worker Recv -> receive method
        $this->assertStringContainsString('public function receivePing(): PingMessage;', $content);
        // Worker Send -> send method
        $this->assertStringContainsString('public function sendPong(PongMessage $message): void;', $content);
    }

    #[Test]
    public function controller_interface_has_dual_directions(): void
    {
        $files = $this->generator->generate($this->simpleGraph());
        $content = $files['src/App/Protocol/TestControllerProtocolInterface.php'];

        // Controller flips: Recv in definition -> Send for controller
        $this->assertStringContainsString('public function sendPing(PingMessage $message): void;', $content);
        // Controller flips: Send in definition -> Recv for controller
        $this->assertStringContainsString('public function receivePong(): PongMessage;', $content);
    }

    #[Test]
    public function implementation_delegates_to_channel(): void
    {
        $files = $this->generator->generate($this->simpleGraph());
        $content = $files['src/App/Worker/TestWorkerProtocol.php'];

        $this->assertStringContainsString('$this->channel->send($message);', $content);
        $this->assertStringContainsString('return $this->channel->receive();', $content);
        $this->assertStringContainsString('public static function createFromChannel(Channel $channel): static', $content);
    }

    #[Test]
    public function generated_files_have_header_comment(): void
    {
        $files = $this->generator->generate($this->simpleGraph());

        foreach ($files as $content) {
            $this->assertStringContainsString('@generated by session-protocol-generator from TestSession', $content);
        }
    }

    #[Test]
    public function branching_send_generates_multiple_send_methods(): void
    {
        $graph = new SessionGraph(
            protocol: new SessionProtocol(
                name: 'Branch',
                workerNamespace: 'App\\Worker',
                controllerNamespace: 'App\\Controller',
            ),
            initialState: 'Choosing',
            transitions: [
                'Choosing' => [
                    new SessionTransition(Direction::Send, FooMessage::class, 'Choosing'),
                    new SessionTransition(Direction::Send, BarMessage::class, 'Choosing'),
                ],
            ],
        );

        $files = $this->generator->generate($graph);
        $workerInterface = $files['src/App/Protocol/BranchWorkerProtocolInterface.php'];

        $this->assertStringContainsString('public function sendFoo(FooMessage $message): void;', $workerInterface);
        $this->assertStringContainsString('public function sendBar(BarMessage $message): void;', $workerInterface);
    }

    #[Test]
    public function branching_recv_generates_union_return_type(): void
    {
        $graph = new SessionGraph(
            protocol: new SessionProtocol(
                name: 'Branch',
                workerNamespace: 'App\\Worker',
                controllerNamespace: 'App\\Controller',
            ),
            initialState: 'Waiting',
            transitions: [
                'Waiting' => [
                    new SessionTransition(Direction::Recv, FooMessage::class, 'Waiting'),
                    new SessionTransition(Direction::Recv, BarMessage::class, 'Waiting'),
                ],
            ],
        );

        $files = $this->generator->generate($graph);
        $workerInterface = $files['src/App/Protocol/BranchWorkerProtocolInterface.php'];

        $this->assertStringContainsString('public function receiveFooOrBar(): FooMessage|BarMessage;', $workerInterface);
    }

    #[Test]
    public function psalm_annotations_are_generated_with_enum_class(): void
    {
        $graph = SessionGraph::fromEnum(PhpReaderSession::class);
        $files = $this->generator->generate($graph);

        $workerInterface = $files['src/Inspector/Daemon/Reader/Protocol/PhpReaderWorkerProtocolInterface.php'];
        $this->assertStringContainsString('@template TState of PhpReaderSession', $workerInterface);
        $this->assertStringContainsString('@psalm-if-this-is PhpReaderWorkerProtocolInterface<PhpReaderSession::AwaitingSettings>', $workerInterface);
        $this->assertStringContainsString('@psalm-this-out PhpReaderWorkerProtocolInterface<PhpReaderSession::AwaitingAttach>', $workerInterface);
    }

    #[Test]
    public function psalm_annotations_omitted_without_enum_class(): void
    {
        $files = $this->generator->generate($this->simpleGraph());
        $workerInterface = $files['src/App/Protocol/TestWorkerProtocolInterface.php'];

        $this->assertStringNotContainsString('@template', $workerInterface);
        $this->assertStringNotContainsString('@psalm-if-this-is', $workerInterface);
        $this->assertStringNotContainsString('@psalm-this-out', $workerInterface);
    }

    #[Test]
    public function throws_on_invalid_graph(): void
    {
        $graph = new SessionGraph(
            protocol: new SessionProtocol(
                name: 'Bad',
                workerNamespace: 'App\\Worker',
                controllerNamespace: 'App\\Controller',
            ),
            initialState: 'S0',
            transitions: [
                'S0' => [], // deadlock: no transitions
            ],
        );

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('Protocol verification failed');
        $this->generator->generate($graph);
    }

    #[Test]
    public function throws_on_nonexistent_message_class(): void
    {
        $graph = new SessionGraph(
            protocol: new SessionProtocol(
                name: 'Bad',
                workerNamespace: 'App\\Worker',
                controllerNamespace: 'App\\Controller',
            ),
            initialState: 'S0',
            transitions: [
                'S0' => [
                    new SessionTransition(Direction::Send, 'App\\NoSuch\\FakeMessage', 'S0'),
                ],
            ],
        );

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('does not exist');
        $this->generator->generate($graph);
    }

    #[Test]
    public function real_protocol_output_matches_committed_files(): void
    {
        $graph = SessionGraph::fromEnum(PhpReaderSession::class);
        $files = $this->generator->generate($graph);

        foreach ($files as $relativePath => $generatedContent) {
            $committedPath = dirname(__DIR__, 4) . '/' . $relativePath;
            if (!file_exists($committedPath)) {
                $this->fail("Expected generated file does not exist: {$relativePath}");
            }
            $committedContent = file_get_contents($committedPath);
            $this->assertSame(
                $committedContent,
                $generatedContent,
                "Generated output for {$relativePath} differs from committed file. Run generator:protocol to update.",
            );
        }
    }

    #[Test]
    public function real_searcher_protocol_output_matches_committed_files(): void
    {
        $graph = SessionGraph::fromEnum(PhpSearcherSession::class);
        $files = $this->generator->generate($graph);

        foreach ($files as $relativePath => $generatedContent) {
            $committedPath = dirname(__DIR__, 4) . '/' . $relativePath;
            if (!file_exists($committedPath)) {
                $this->fail("Expected generated file does not exist: {$relativePath}");
            }
            $committedContent = file_get_contents($committedPath);
            $this->assertSame(
                $committedContent,
                $generatedContent,
                "Generated output for {$relativePath} differs from committed file. Run generator:protocol to update.",
            );
        }
    }
}
