<?php

/**
 * This file is part of the reliforp/reli-prof package.
 *
 * (c) sji <sji@sj-i.dev>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Reli\Lib\Session;

/**
 * Checks that call sites of union-typed receive methods handle all message types
 * via instanceof checks.
 */
final class RecvBranchExhaustivenessChecker
{
    /**
     * @param list<BranchRecvMethod> $branchRecvMethods
     * @param string $srcDir Directory to scan for call sites
     * @return list<string> List of warnings
     */
    public function check(array $branchRecvMethods, string $srcDir): array
    {
        if ($branchRecvMethods === []) {
            return [];
        }

        $warnings = [];
        $phpFiles = $this->collectPhpFiles($srcDir);

        foreach ($branchRecvMethods as $method) {
            $callSites = $this->findCallSites($method->methodName, $phpFiles);

            if ($callSites === []) {
                continue;
            }

            foreach ($callSites as $filePath) {
                $content = file_get_contents($filePath);
                if ($content === false) {
                    continue;
                }

                // Skip generated protocol implementations (they just delegate to channel)
                if (str_contains($content, '@generated by session-protocol-generator')) {
                    continue;
                }

                $missingTypes = $this->findMissingInstanceofChecks(
                    $content,
                    $method->messageClassShortNames,
                );

                if ($missingTypes !== []) {
                    $relative = $this->relativePath($filePath, $srcDir);
                    $warnings[] = sprintf(
                        "%s: %s() returns %s, but %s %s never checked via instanceof",
                        $relative,
                        $method->methodName,
                        implode('|', $method->messageClassShortNames),
                        implode(', ', $missingTypes),
                        count($missingTypes) === 1 ? 'is' : 'are',
                    );
                }
            }
        }

        return $warnings;
    }

    /**
     * Extract branch recv methods from a SessionGraph.
     *
     * @return list<BranchRecvMethod>
     */
    public static function extractBranchRecvMethods(SessionGraph $graph): array
    {
        $methods = [];

        foreach ($graph->transitions as $state => $transitions) {
            if (count($transitions) <= 1) {
                continue;
            }

            // Only Recv states with multiple transitions are branching
            if ($transitions[0]->direction !== Direction::Recv) {
                continue;
            }

            $shortNames = array_map(
                fn (SessionTransition $t) => self::shortName($t->messageClass),
                $transitions,
            );

            // Method name follows the generator's naming convention
            $basenames = array_map(
                fn (string $short) => preg_replace('/Message$/', '', $short),
                $shortNames,
            );
            $methodName = 'receive' . implode('Or', $basenames);

            $methods[] = new BranchRecvMethod(
                state: $state,
                methodName: $methodName,
                messageClasses: array_map(
                    fn (SessionTransition $t) => $t->messageClass,
                    $transitions,
                ),
                messageClassShortNames: $shortNames,
            );
        }

        return $methods;
    }

    /**
     * @return list<string>
     */
    private function collectPhpFiles(string $dir): array
    {
        $files = [];
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS),
        );

        foreach ($iterator as $file) {
            assert($file instanceof \SplFileInfo);
            if ($file->getExtension() === 'php') {
                $files[] = $file->getPathname();
            }
        }

        return $files;
    }

    /**
     * @param list<string> $phpFiles
     * @return list<string> File paths containing calls to the method
     */
    private function findCallSites(string $methodName, array $phpFiles): array
    {
        $sites = [];
        foreach ($phpFiles as $file) {
            $content = file_get_contents($file);
            if ($content !== false && str_contains($content, $methodName)) {
                $sites[] = $file;
            }
        }
        return $sites;
    }

    /**
     * @param list<string> $shortNames
     * @return list<string> Short names not found in instanceof checks
     */
    private function findMissingInstanceofChecks(string $content, array $shortNames): array
    {
        $missing = [];
        foreach ($shortNames as $short) {
            // Match: instanceof ShortName, instanceof \Full\ShortName, or ShortName::class
            if (
                !preg_match('/instanceof\s+(?:\\\\[\w\\\\]+\\\\)?' . preg_quote($short, '/') . '\b/', $content)
                && !preg_match('/' . preg_quote($short, '/') . '::class/', $content)
            ) {
                $missing[] = $short;
            }
        }
        return $missing;
    }

    private static function shortName(string $fqcn): string
    {
        $parts = explode('\\', $fqcn);
        return end($parts);
    }

    private function relativePath(string $filePath, string $srcDir): string
    {
        $prefix = rtrim($srcDir, '/') . '/';
        if (str_starts_with($filePath, $prefix)) {
            return substr($filePath, strlen($prefix));
        }
        return $filePath;
    }
}
