<?php

/**
 * This file is part of the reliforp/reli-prof package.
 *
 * (c) sji <sji@sj-i.dev>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @generated by session-protocol-generator from PhpReaderSession
 */

declare(strict_types=1);

namespace Reli\Inspector\Daemon\Reader\Controller;

use Amp\Sync\Channel;
use Reli\Inspector\Daemon\Reader\Protocol\Message\AttachMessage;
use Reli\Inspector\Daemon\Reader\Protocol\Message\DetachWorkerMessage;
use Reli\Inspector\Daemon\Reader\Protocol\Message\SetSettingsMessage;
use Reli\Inspector\Daemon\Reader\Protocol\Message\TraceMessage;
use Reli\Inspector\Daemon\Reader\Protocol\PhpReaderControllerProtocolInterface;
use Reli\Inspector\Daemon\Reader\Protocol\PhpReaderSession;

/**
 * @template TState of PhpReaderSession
 * @implements PhpReaderControllerProtocolInterface<TState>
 */
final class PhpReaderControllerProtocol implements PhpReaderControllerProtocolInterface
{
    public function __construct(
private Channel $channel
    ) {
    }

    /** @return self<PhpReaderSession::AwaitingSettings> */
    public static function createFromChannel(Channel $channel): static
    {
return new self($channel);
    }

    /**
     * @psalm-if-this-is PhpReaderControllerProtocol<PhpReaderSession::AwaitingSettings>
     * @psalm-this-out PhpReaderControllerProtocol<PhpReaderSession::AwaitingAttach>
     */
    public function sendSetSettings(SetSettingsMessage $message): void
    {
$this->channel->send($message);
    }

    /**
     * @psalm-if-this-is PhpReaderControllerProtocol<PhpReaderSession::AwaitingAttach>
     * @psalm-this-out PhpReaderControllerProtocol<PhpReaderSession::Tracing>
     */
    public function sendAttach(AttachMessage $message): void
    {
$this->channel->send($message);
    }

    /**
     * @psalm-if-this-is PhpReaderControllerProtocol<PhpReaderSession::Tracing>
     * @psalm-this-out PhpReaderControllerProtocol<PhpReaderSession::Tracing|PhpReaderSession::AwaitingAttach>
     */
    public function receiveTraceOrDetachWorker(): TraceMessage|DetachWorkerMessage
    {
/** @var TraceMessage|DetachWorkerMessage */
return $this->channel->receive();
    }
}
