<?php

/**
 * This file is part of the reliforp/reli-prof package.
 *
 * (c) sji <sji@sj-i.dev>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Reli\Tools\Rector;

use PhpParser\Node;
use PhpParser\Node\Expr\ConstFetch;
use PhpParser\Node\Expr\Closure;
use PhpParser\Node\Expr\ArrowFunction;
use PhpParser\Node\Name;
use PhpParser\Node\NullableType;
use PhpParser\Node\Param;
use PhpParser\Node\Stmt\ClassMethod;
use PhpParser\Node\Stmt\Function_;
use Rector\Rector\AbstractRector;
use Symplify\RuleDocGenerator\ValueObject\CodeSample\CodeSample;
use Symplify\RuleDocGenerator\ValueObject\RuleDefinition;

/**
 * Downgrade `?T` nullable type hints (PHP 7.1+) for PHP 7.0 compatibility.
 *
 * Parameters: drop the type entirely and ensure a `= null` default is set.
 *
 *   ?T $x = null  ->  $x = null
 *   ?T $x         ->  $x = null
 *   ?T $x = 5     ->  $x = 5
 *
 * The naive translation `?T $x = null` -> `T $x = null` (implicit nullable)
 * was deprecated in PHP 8.4 and is scheduled to become an error in PHP 9.0.
 * Generating it would emit a fatal-future deprecation warning every time
 * the class is autoloaded on PHP 8.4+, polluting end-user error logs.
 * Stripping the type entirely keeps the code working on every supported
 * PHP version (7.0 .. 8.5+) without runtime warnings; type information
 * is preserved in the `@param` docblocks generated by Rector's existing
 * downgrade rules.
 *
 * Return types:
 *   function foo(): ?T    ->  function foo()   (PHP 7.0 has no nullable return form)
 *
 * The official Rector downgrade level set stops at PHP 7.1, so the 7.1 -> 7.0
 * gap is filled by this rule and its siblings. See rector-sidecar-client.php.
 */
final class DowngradeNullableTypeToPhp70Rector extends AbstractRector
{
    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition(
            'Strip ?T nullable types for PHP 7.0 compatibility (without triggering the PHP 8.4 implicit-nullable deprecation)',
            [new CodeSample(
                'public function foo(?string $x): ?int { return null; }',
                'public function foo($x = null) { return null; }',
            )],
        );
    }

    /**
     * @return array<class-string<Node>>
     */
    public function getNodeTypes(): array
    {
        return [
            Param::class,
            ClassMethod::class,
            Function_::class,
            Closure::class,
            ArrowFunction::class,
        ];
    }

    public function refactor(Node $node): ?Node
    {
        if ($node instanceof Param) {
            return $this->refactorParam($node);
        }

        return $this->refactorReturn($node);
    }

    private function refactorParam(Param $param): ?Param
    {
        if (!$param->type instanceof NullableType) {
            return null;
        }

        $param->type = null;
        if ($param->default === null) {
            $param->default = new ConstFetch(new Name('null'));
        }
        return $param;
    }

    /**
     * @param ClassMethod|Function_|Closure|ArrowFunction $node
     */
    private function refactorReturn(Node $node): ?Node
    {
        if (!$node->returnType instanceof NullableType) {
            return null;
        }

        $node->returnType = null;
        return $node;
    }
}
